apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-team-gamma
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.31.0
    helm:
      releaseName: team-gamma
      values: |
        controlPlane:
          distro:
            k3s:
              enabled: true
        sync:
          toHost:
            pods:
              enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: team-gamma
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true