apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/robinmetro1/vcluster-gitops-platform.git
      revision: HEAD
      directories:
      - path: "vclusters/*.yaml"
  
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/robinmetro1/vcluster-gitops-platform.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
