apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/robinmetro1/vcluster-gitops-platform.git
      revision: HEAD
      files:
      - path: "vclusters/*.yaml"
  
  template:
    metadata:
      name: 'vcluster-{{path.basenameNormalized}}'
      namespace: argocd
      labels:
        app: vcluster
        team: '{{path.basenameNormalized}}'
    
    spec:
      project: default
      
      source:
        repoURL: https://charts.loft.sh
        chart: vcluster
        targetRevision: 0.20.0
        helm:
          releaseName: '{{path.basenameNormalized}}'
          values: |
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            storage:
              size: 5Gi
            isolation:
              enabled: true
            coredns:
              enabled: true
            syncer:
              extraArgs:
                - --tls-san={{path.basenameNormalized}}.local
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basenameNormalized}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
